# Collaboration Kit backend for clustering support
com.vaadin.experimental.collaborationEngineBackend=true
# Server side WebPush API
com.vaadin.experimental.webPush=true
# Form Filler Add-on
com.vaadin.experimental.formFillerAddon=true
# Hilla I18n API
com.vaadin.experimental.hillaI18n=true
# Hilla Full-stack Signals
com.vaadin.experimental.fullstackSignals=true
# Copilot experimental features
com.vaadin.experimental.copilotExperimentalFeatures=true
